version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  goinventory-api:
    lang: dockerfile
    handler: ./goinventory-api
    image: yonglexu/goinventory-api:latest
configuration:
  templates:
    - name: dockerfile