version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  goinventory-api:
    lang: dockerfile
    handler: ./goinventory-api
    image: ghcr.io/quasaer/goinventory-api:latest
    secrets:
    - inventory-postgres-connection-string
  inventory-frontend:
    lang: dockerfile
    handler: ./inventory-frontend
    image: yonglexu/inventory-frontend:latest
configuration:
  templates:
    - name: dockerfile  

