version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  goinventory-api:
    lang: golang-middleware
    handler: ./goinventory-api
    image: ghcr.io/quasaer/goinventory-api:latest
configuration:
  templates:
    - name: golang-middleware